### PR TITLE
Unit test for bad dates

### PR DESCRIPTION
**Pull request by burkmarr**
Merge request for the purposes of seeing results of Travis CI unit test.

### CODE REVIEW

**Comment by johnvanbreda** [comment]
Just noting in case you didn't work this out - for things like this you can create a branch from develop, then publish the branch so it gets tested by Travis without pull requesting into Develop until you are happy.

**Comment by burkmarr** [comment]
No I didn't work that out - I thought there probably was a better way than making a pull request though! I'm still not sure exactly what you mean - how do you 'publish' a branch?

**Comment by johnvanbreda** [comment]
You can use the Sync button in GitHub desktop, or from the command line here's a full example:
```bash
$ git checkout develop
$ git checkout -b feature-myfeature
(make changes)
$ git commit -a
$ git push --set-upstream origin feature-myfeature
```

You probably want to delete the branch on GitHub once finished.

**Comment by burkmarr** [comment]
Hi John. That's the workflow I already use. So I had the branch on GitHub but I couldn't see how to run the unit tests without making the 'fake' pull request.

**Pull request closed without merging**
