### PR TITLE
Feature response external keys

### PR DESCRIPTION
**Pull request by johnvanbreda**
External keys in warehouse responses.

### CODE REVIEW

**Comment by kazlauskis** [comment]
Thanks, I am not familiar with the warehouse workings, so my question is whether external keys will be returned for the outer model only or its children too?

**Comment by johnvanbreda** [comment]
Yes, here's an example:
```
array (
  'success' => 'multiple records',
  'outer_table' => 'sample',
  'outer_id' => 863,
  'struct' => 
  array (
    'model' => 'sample',
    'id' => 863,
    'external_key' => 'TESTSAMP',
    'children' => 
    array (
      0 => 
      array (
        'model' => 'occurrence',
        'id' => 843,
        'external_key' => 'TESTOCC',
        ),
      ),
    ),
  ),
  'outer_external_key' => 'TESTSAMP',
)
```

Thinking about it, there would be some merit in the response format matching your proposed JSON submission format (even if it only includes the key fields).

**Comment by kazlauskis** [comment]
Yes, that also would be also excellent. For synchronisation, it would also be very useful to return the exact timestamp of the resource creation, as this would help to check if models on the client have been changed.

**Comment by johnvanbreda** [comment]
Hi @kazlauskis 
I'm also wondering if I should drop the "outer_external_key" since you can just use the contents of the "struct" to get this. So, if you want timestamps included, the above example would become:
```
array (
  'success' => 'multiple records',
  'outer_table' => 'sample',
  'outer_id' => 863,
  'struct' => 
  array (
    'model' => 'sample',
    'id' => 863,
    'external_key' => 'TESTSAMP',
    'created_on' => '2017-02-10 09:01:36',
    'updated_on' => '2017-02-10 09:01:36',
    'children' => 
    array (
      0 => 
      array (
        'model' => 'occurrence',
        'id' => 843,
        'external_key' => 'TESTOCC',
        'created_on' => '2017-02-10 09:01:36',
        'updated_on' => '2017-02-10 09:01:36',
        ),
      ),
    ),
  ),
)
```

Is that OK?

**Comment by kazlauskis** [comment]
If it stores the timestamps in milliseconds then I would return those, but otherwise, this looks great. Thanks!

**Comment by johnvanbreda** [comment]
Ok, I'll try and do this later today.

**Comment by johnvanbreda** [comment]
Closing pull request as I've created a different branch with the refined changes in.

**Pull request closed without merging**
