### PR TITLE
Hotfix core text censor

### PR DESCRIPTION
**Pull request by JimBacon**

### CODE REVIEW

**Comment by johnvanbreda** [comment]
Jim, is editing the core system version of this file necessary, or can the text.php changes become a My_text.php file under the application folder?

**Comment by JimBacon** [comment]
Well, we are now effectively the maintainers of this fork of Kohana. If you think of yourself as the Kohana maintainer as well as Indicia, where would you choose to fix it? I think this is the simpler solution. I imagine there will be more such things to rectify, some only possible within core, so this could become something to get used to. What argument is there against patching core?

**Comment by johnvanbreda** [comment]
If you consider us the maintainers of this fork, then I agree. Just wanted to make sure you were aware of the possibility.
I'd advocate bug fixes and core features could go in system, whereas Indicia specifics go under application.

**Comment by JimBacon** [comment]
I don't think there is anyone else in the world I could consider the maintainer of Kohana 2.3! I completely agree with keeping the distinction between system and application to ensure we don't make moving to a different framework any more painful.

**Comment by JimBacon** [comment]
I found the archive repository for Kohana 2 at https://github.com/kohana/kohana2. It contains numerous bug fixes relative to version 2.3.4 which we are using. We might want to merge these in to our repository.

**Pull request merged**
